### ISSUE TITLE
Build failed when use video palyer

### ISSUE THREAD

**Issue by hussenIbrahim** [flutter-tizen/plugins#178] opened 2021-08-14 11:21 UTC
build failed when try to run the video_player example
`Exception: Failed to build native plugins:                              
[PLATFORM] flutter-null
[ARCHITECTURE] i586
[COMPILER] LLVM-10.0
[CONFIGURATION] Debug
[SBI] prdefine options = 
[SBI] command : cmd /c make.exe -f "C:\tizen-studio\tools\ide\resources\native\Build\makefile" -r 
make -f C:\tizen-studio\tools\ide\resources\native\Build/makefile.mk
C:\tizen-studio\tools\smart-build-interface\..\msys2\usr\bin\make[1]: Entering directory
'/c/Users/Hussen/AppData/Local/Temp/flutter_tools.406f3168/38784c99'
find: ‘C:UsersHussenflutter-tizenflutterbincacheartifactsenginetizen-commoncpp_client_wrapper*.cc’: No such file 
or directory
C:\tizen-studio\tools\ide\resources\native\Build/makefile.mk:160: warning: overriding recipe for target 'Debug'  
C:\tizen-studio\tools\ide\resources\native\Build/makefile.mk:157: warning: ignoring old recipe for target 'Debug'  Building target: Debug/libflutter_plugins.so
  Invoking: C/C++ Linker
"C:\tizen-studio\tools\smart-build-interface/../llvm-10/bin/clang++.exe" -o ./Debug/libflutter_plugins.so        
@./Debug/target_objs.file  -lvideo_player_tizen_plugin
-L"C:/Users/Hussen/AppData/Local/Temp/flutter_tools.406f3168/38784c99/lib" -Wl,--no-undefined
-Wl,-rpath='$ORIGIN' -target i586-tizen-linux-gnueabi -gcc-toolchain
"C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/" -ccc-gcc-name i586-linux-gnueabi-g++-march=i586 -Wl,-z,relro,--as-needed,-z,noseparate-code -static-libstdc++ -Xlinker --as-needed -shared -lpthread 
--sysroot="C:/tizen-studio/platforms/tizen-4.0/wearable/rootstraps/wearable-4.0-emulator.core"
-LC:/tizen-studio/platforms/tizen-4.0/wearable/rootstraps/wearable-4.0-emulator.core/usr/lib
@./Debug/platform_libs.file -lflutter_tizen_tv
-L"/c/Users/Hussen/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-x86-debug"
-I"/c/Users/Hussen/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include"     
-I"/c/Users/Hussen/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public"
-L"/f/projects/test_app/.dart_tool/flutter_build/718903dc87706f4568e0721753455894/tizen_plugins/lib"
-Wl,--undefined=VideoPlayerTizenPluginRegisterWithRegistrar
C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../../../i586-tizen-linux-gnueabi/bin\ld:
F:/projects/test_app/.dart_tool/flutter_build/718903dc87706f4568e0721753455894/tizen_plugins/lib\libvideo_player_tizen_plugin.a(video_player_tizen_plugin.o): in function
`VideoPlayerTizenPlugin::RegisterWithRegistrar(flutter::PluginRegistrar*, flutter::TextureRegistrar*)':
C:\Users\Hussen\AppData\Local\Temp\flutter_tools.406f3168\8a1600a1/src/video_player_tizen_plugin.cc:54: undefinedreference to `flutter::PluginRegistrar::AddPlugin(std::unique_ptr<flutter::Plugin,
std::default_delete<flutter::Plugin> >)'
C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../../../i586-tizen-linux-gnueabi/bin\ld:
F:/projects/test_app/.dart_tool/flutter_build/718903dc87706f4568e0721753455894/tizen_plugins/lib\libvideo_player_tizen_plugin.a(video_player_tizen_plugin.o): in function `VideoPlayerTizenPluginRegisterWithRegistrar':
C:\Users\Hussen\AppData\Local\Temp\flutter_tools.406f3168\8a1600a1/src/video_player_tizen_plugin.cc:224:
undefined reference to `flutter::PluginRegistrarManager::GetInstance()'
C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../../../i586-tizen-linux-gnueabi/bin\ld:
C:\Users\Hussen\AppData\Local\Temp\flutter_tools.406f3168\8a1600a1/src/video_player_tizen_plugin.cc:226:
undefined reference to `flutter::PluginRegistrarManager::GetInstance()'
C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../../../i586-tizen-linux-gnueabi/bin\ld:
F:/projects/test_app/.dart_tool/flutter_build/718903dc87706f4568e0721753455894/tizen_plugins/lib\libvideo_player_tizen_plugin.a(video_player_tizen_plugin.o): in function `flutter::PluginRegistrar*
flutter::PluginRegistrarManager::GetRegistrar<flutter::PluginRegistrar>(FlutterDesktopPluginRegistrar*)':        
C:/Users/Hussen/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include\flutter/plugin_registrar.h:106: undefined reference to
`flutter::PluginRegistrarManager::OnRegistrarDestroyed(FlutterDesktopPluginRegistrar*)'
C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../../../i586-tizen-linux-gnueabi/bin\ld:
F:/projects/test_app/.dart_tool/flutter_build/718903dc87706f4568e0721753455894/tizen_plugins/lib\libvideo_player_tizen_plugin.a(video_player_tizen_plugin.o): in function
`std::_MakeUniq<flutter::PluginRegistrar>::__single_object std::make_unique<flutter::PluginRegistrar,
FlutterDesktopPluginRegistrar*&>(FlutterDesktopPluginRegistrar*&)':
C:\/tizen-studio\tools\smart-build-interface\..\i586-linux-gnueabi-gcc-9.2\lib\gcc\i586-tizen-linux-gnueabi\9.2.0\..\..\..\..\i586-tizen-linux-gnueabi\include\c++\9.2.0\bits\unique_ptr.h:849: undefined reference to
`flutter::PluginRegistrar::PluginRegistrar(FlutterDesktopPluginRegistrar*)'
C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../../../i586-tizen-linux-gnueabi/bin\ld:
F:/projects/test_app/.dart_tool/flutter_build/718903dc87706f4568e0721753455894/tizen_plugins/lib\libvideo_player_tizen_plugin.a(message.o): in function `VideoPlayerApi::setup(flutter::BinaryMessenger*, VideoPlayerApi*)':      
C:\Users\Hussen\AppData\Local\Temp\flutter_tools.406f3168\8a1600a1/src/message.cc:333: undefined reference to    
`flutter::StandardMessageCodec::GetInstance(flutter::StandardCodecSerializer const*)'
C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../../../i586-tizen-linux-gnueabi/bin\ld:
C:\Users\Hussen\AppData\Local\Temp\flutter_tools.406f3168\8a1600a1/src/message.cc:355: undefined reference to    
`flutter::StandardMessageCodec::GetInstance(flutter::StandardCodecSerializer const*)'
C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../../../i586-tizen-linux-gnueabi/bin\ld:
C:\Users\Hussen\AppData\Local\Temp\flutter_tools.406f3168\8a1600a1/src/message.cc:377: undefined reference to    
`flutter::StandardMessageCodec::GetInstance(flutter::StandardCodecSerializer const*)'
C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../../../i586-tizen-linux-gnueabi/bin\ld:
C:\Users\Hussen\AppData\Local\Temp\flutter_tools.406f3168\8a1600a1/src/message.cc:400: undefined reference to    
`flutter::StandardMessageCodec::GetInstance(flutter::StandardCodecSerializer const*)'
C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../../../i586-tizen-linux-gnueabi/bin\ld:
C:\Users\Hussen\AppData\Local\Temp\flutter_tools.406f3168\8a1600a1/src/message.cc:423: undefined reference to    
`flutter::StandardMessageCodec::GetInstance(flutter::StandardCodecSerializer const*)'
C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../../../i586-tizen-linux-gnueabi/bin\ld:
F:/projects/test_app/.dart_tool/flutter_build/718903dc87706f4568e0721753455894/tizen_plugins/lib\libvideo_player_tizen_plugin.a(message.o):C:\Users\Hussen\AppData\Local\Temp\flutter_tools.406f3168\8a1600a1/src/message.cc:446: 
more undefined references to `flutter::StandardMessageCodec::GetInstance(flutter::StandardCodecSerializer        
const*)' follow
C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../../../i586-tizen-linux-gnueabi/bin\ld:
F:/projects/test_app/.dart_tool/flutter_build/718903dc87706f4568e0721753455894/tizen_plugins/lib\libvideo_player_tizen_plugin.a(video_player.o): in function `VideoPlayer::setupEventChannel(flutter::BinaryMessenger*)':
C:\Users\Hussen\AppData\Local\Temp\flutter_tools.406f3168\8a1600a1/src/video_player.cc:319: undefined reference  
to `flutter::StandardMethodCodec::GetInstance(flutter::StandardCodecSerializer const*)'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
C:\tizen-studio\tools\smart-build-interface\..\msys2\usr\bin\make[1]: ***
[C:\tizen-studio\tools\ide\resources\native\Build/makefile.mk:151: Debug/libflutter_plugins.so] Error 1
C:\tizen-studio\tools\smart-build-interface\..\msys2\usr\bin\make[1]: Leaving directory
'/c/Users/Hussen/AppData/Local/Temp/flutter_tools.406f3168/38784c99'
make: *** [C:\tizen-studio\tools\ide\resources\native\Build\makefile:27: app_build] Error 2
Total time: 00:00:02.778`

**Comment by swift-kim** [comment] 2021-08-14 12:21
Sorry for the inconvenience and thanks for reporting!

It looks like an error caused by a recent change in the flutter-tizen tool: https://github.com/flutter-tizen/flutter-tizen/pull/195.

I already prepared a fix: https://github.com/flutter-tizen/flutter-tizen/pull/197. The change will be merged in a few days but you can checkout the commit to try out earlier.

**Closed** 2021-08-15 04:46 UTC
Labels: bug
