### ISSUE TITLE
[video_player] HLS issue in video plugin

### ISSUE THREAD

**Issue by xuelian-bai** [flutter-tizen/plugins#304] opened 2021-12-14 06:13 UTC
Platform Tizen 6.0 - Samsung The Frame 2021

We checked several streams. It seems that the problem ist not HLS v4 because this stream works

http://amssamples.streaming.mediaservices.windows.net/91492735-c523-432b-ba01-faba6c2206a2/AzureMediaServicesPromo.ism/manifest(format=m3u8-aapl)

Also tested v5 - no problem.
![ok](https://user-images.githubusercontent.com/92981432/145411290-f8ea9258-8696-499d-82a8-dfa40116dd60.png)

Our streams aren't that different - but we got teletext streams - maybe that is the problem?
Or HLS Live Stream?

![fail1](https://user-images.githubusercontent.com/92981432/145411487-e2ba850d-4910-45a6-afe1-47807893764a.png)
![fail2](https://user-images.githubusercontent.com/92981432/145411572-b032b245-89b1-4f0e-b2b1-aee05014cc39.png)

_Originally posted by @mhoeckner in https://github.com/flutter-tizen/flutter-tizen/issues/217#issuecomment-989886695_

**Comment by xuelian-bai** [comment] 2021-12-14 06:15
@mhoeckner could you please share more details about your stream? I will send this issue to HLS maintainer

**Comment by mhoeckner** [comment] 2021-12-15 12:28
Dear @xuelian-bai 

sorry for the late answer - I talked to technical guys to provide a test stream. 

Please contact me via E-Mail - I will send you the HLS Stream URL without authentication. 

It's HLS v4 with AAC and MP4 

markus.hoeckner AT ocilion.com

**Comment by xiaowei-guan** [comment] 2021-12-23 06:48
@mhoeckner With you test stream, we found duration is zero after player is prepared. this will cause video player crash, and I have made a PR for this issue.
# https://github.com/flutter/plugins/pull/4635

**Comment by mhoeckner** [comment] 2022-02-18 09:13
@xiaowei-guan 

The ticket has been closed - at flutter - what will be the next steps? Are you still working on this issue?
I ask because we need to know if this will work in future because of project planing - upcoming new versions - and so on  :)

**Comment by xiaowei-guan** [comment] 2022-02-21 02:27
@mhoeckner Hello, because of this issue can't be reproduced on Android or IOS device, flutter team has not  decided to accept this PR, and  this video player plugin is based on MMplayer, and it will be not maintained anymore on TV device. So we are developing a new video player plugin with plus player for TV device, when we complete it, we will notify you.

**Comment by mhoeckner** [comment] 2022-02-21 06:10
@xiaowei-guan 

Thank you for the information and improvements. One last question: will the new player be available on older platforms like Tizen 5.5 or only 6.0+ ?

**Comment by ale-russ-kabbee** [comment] 2022-10-11 07:45
Any update on the new video player for TV devices, and will it be able to play videos in tizen tv 
emulators

**Comment by mhoeckner** [comment] 2022-10-11 08:03
I do not think that this is possible - especially if you use DRM protected content

**Comment by xuelian-bai** [comment] 2022-10-12 07:15
> Any update on the new video player for TV devices, and will it be able to play videos in tizen tv emulators

We will release a new video player recently, it can play video on TV device, I will let you know if it can play video on emulators soon.

**Comment by xuelian-bai** [comment] 2022-10-12 07:16
> I do not think that this is possible - especially if you use DRM protected content

DRM content can't play on emulator, but it can on TV device, just developers have to get partner level to run on TV devices.

**Comment by keanallen** [comment] 2023-06-15 07:11
Any update on playing video on emulators? Please

**Comment by swift-kim** [comment] 2023-06-15 07:27
The new video_player plugin mentioned above is [video_player_videohole](https://github.com/flutter-tizen/plugins/tree/master/packages/video_player_videohole), but it doesn't support emulators. There is no way to play DRM content on TV emulators. You need a real TV device.

@xuelian-bai Can we close this issue?

**Comment by xuelian-bai** [comment] 2023-06-15 07:43
hmm. this is issue of emulator actually, emulator is not maintained by us. As @swift-kim  mentioned, DRM content can't be play on emulator(because there is no trustzone), and also hardware decoder on TV is different from decoder on emulator, so I recommend you to have a TV device for video playing

**Comment by xuelian-bai** [comment] 2023-06-15 08:29
@keanallen with this plugin https://github.com/flutter-tizen/plugins/tree/master/packages/video_player_videohole, you can at least play the example mp4 on emulator, please try to run the example

**Comment by keanallen** [comment] 2023-06-15 08:43
@xuelian-bai do i need to import `video_player_tizen` along with `video_player_videohole`?

**Comment by xuelian-bai** [comment] 2023-06-15 08:44
no, you don't need to import, they are different plugins

**Comment by keanallen** [comment] 2023-06-15 08:45
Alright, thank you so much @xuelian-bai .
Btw, which do you suggest? `video_player_tizen ` or `video_player_videohole `?

I will only creating tv app in tizen

**Comment by xuelian-bai** [comment] 2023-06-15 08:51
you can use video_player_videohole, it can play the mp4 in example on emulator, but some videos may not be play normally since it didn't use hardware decoder on emulator.

**Comment by xiaowei-guan** [comment] 2023-06-15 08:55
![play_sample_mp4_emul](https://github.com/flutter-tizen/plugins/assets/60122246/b34b0228-c210-4cd2-a4fd-aa3a341c8b04)

**Comment by keanallen** [comment] 2023-06-15 09:17
`import 'package:video_player_videohole/video_player.dart';`

```bashrc
Target of URI doesn't exist: 'package:video_player_videohole/video_player.dart'.
Try creating the file referenced by the URI, or try using a URI for a file that does exist.dart[uri_does_not_exist](https://dart.dev/diagnostics/uri_does_not_exist)
```

**Comment by swift-kim** [comment] 2023-06-15 14:47
@keanallen Have you run `flutter-tizen pub get` (CLI) or `Pub: Get Packages` (VS Code)? You may also try running `Dart: Restart Analysis Server` (VS Code) if the problem persists.

**Closed** 2023-11-27 06:19 UTC
Labels: bug
